export const dataNav = {
  aboutEN: "About",
  aboutID: "Tentang",
  meEN: "Me",
  meID: "Saya",
  homeEN: "Home",
  homeID: "Beranda",
  profilEN: "Profil",
  profilID: "Profil",
  portfolioEN: "Portfolio",
  portfolioID: "Portofolio",
  contactEN: "Contact",
  contactID: "Kontak",
};

export const dataHome = {
  helloEN: "Hello, Welcome!",
  helloID: "Halo, Selamat Datang!",
  introEN: "I'm Muhamad Aqil Maulana",
  introID: "Saya Muhamad Aqil Maulana",
  quotesEN: "Must be professional. I'm satisfied, I'm sure you should be satisfied too.",
  quotesID: "Harus profesional. Saya puas, saya pastikan Anda pun harus puas juga.",
  imageUrl: [
    "https://i.imgur.com/zVPt21R.jpg",
    "https://i.imgur.com/RSrycl2.jpg",
    "https://i.imgur.com/b0N0E35.jpg",
    "https://i.imgur.com/ErF9qMf.jpg",
    "https://i.imgur.com/0SGyP4P.jpg",
    "https://i.imgur.com/7eEM19M.jpg",
    "https://i.imgur.com/vGthHop.jpg",
  ],
  profEN: [
    {
      id: "penull",
      profName: "Select Prof",
    },
    {
      id: "pefe",
      profName: "Front End Developer",
    },
    {
      id: "pewr",
      profName: "Writer & Translation",
    },
    {
      id: "peve",
      profName: "Video Editor",
    },
  ],
  profID: [
    {
      id: "pinull",
      profName: "Pilih Profesi",
    },
    {
      id: "pife",
      profName: "Front End Developer",
    },
    {
      id: "piwr",
      profName: "Penulis & Penerjemah",
    },
    {
      id: "pive",
      profName: "Video Editor",
    },
  ],
  medsos: [
    {
      id: "hmi",
      name: "Instagram",
      src: "https://i.imgur.com/cS1ZUqn.png",
      href: "https://www.instagram.com/aqil.co.id/",
    },
    {
      id: "hmf",
      name: "Facebook",
      src: "https://i.imgur.com/sRxt5z8.png",
      href: "https://www.facebook.com/muhammadaqil2514",
    },
    {
      id: "hmt",
      name: "Twitter",
      src: "https://i.imgur.com/B0oZ4sf.png",
      href: "https://twitter.com/aqil2514",
    },
    {
      id: "hmg",
      name: "Github",
      src: "https://i.imgur.com/m2B40Um.png",
      href: "https://github.com/aqil2514/",
    },
    {
      id: "hmcp",
      name: "CodePen",
      src: "https://i.imgur.com/s4kVOmt.png",
      href: "https://codepen.io/aqil2514",
    },
  ],
};

export const dataProfil = {
  descId: "Halo! Saya Muhamad Aqil Maulana dan Akrab dipanggil Aqil.",
  descEn: "Hello! I`m Muhamad Aqil Maulana and you can call me Aqil.",
  purposeId: "Tujuan saya membuat portofolio ini untuk memberitahu mengenai karya apa saja yang sudah saya buat dalam berbagai bidang yang saya tekuni.",
  purposeEn: "My aim in creating this portfolio is to share about my work that I`ve made in any various fields I work in.",
  educationId:
    "SMA saya di MAN 13 Jakarta dan mengambil jurusan bahasa Jepang. Kemudian, saya masuk ke perguruan tinggi UIN Syarif Hidayatullah Jakarta jurusan Tarjamah (Penerjemahan Arab-Indonesia). Namun, saya juga mempelajari coding secara otodidak.",
  educationEn:
    "My Senior High Scholl is in MAN 13 Jakarta in majoring Japanese Language. Then, I study in UIN Syarif Hidayatullah Jakarta in majoring Tarjamah (Arabic-Indonesian Translation). But, I`ve been also learning coding knowledge by my self.",
  codingId:
    "Untuk saat ini, saya lebih mengarah ke Front End Developer, sehingga saya baru menguasai HTML, CSS, JS, jQuery, Bootstrap, React JS, dan SASS. Saya masih terus mendalami bidang ini dan akan ada hal baru yang saya kuasai nantinya.",
  codingEn:
    "Currently, I am more towards Front End Developer, so I have only mastered HTML, CSS, JS, jQuery, Bootstrap, React JS, and SASS. I am still continuing to explore this field and there will be new things that I master in the future.",
  writeId:
    "Saya juga seorang penulis dan penerjemah. Saya sudah menulis total lebih dari 500 artikel secara online di berbagai media seperti, Kompasiana, IDN Times, Urban Depok, dan Fero`s Blog (Blog Pribadi). Saya juga pernah menerbitkan buku fisik di penerbit GuePedia.",
  writeEn:
    "I am also a writer and translator. I have written a total of more than 500 articles online in various media such as Kompasiana, IDN Times, Urban Depok, and Fero`s Blog (Personal Blog). I have also published physical books at the GuePedia publishing house.",
  videoId:
    "Selain itu, saya juga sedikit menguasai tentang editing video. Namun, bidang ini masih belum saatnya saya perdalam lagi. Tapi, ada beberapa karya video yang pernah saya buat dahulu. Mungkin tidak ada salahnya juga saya tampilkan pada portofolio ini.",
  videoEn:
    "Apart from that, I also know a little about video editing. However, it is not time for me to deepen this field further. However, there are several video works that I have made before. Maybe there's no harm in featuring it in this portfolio.",
  closingId: "Selamat melihat-lihat portoflio saya. Anda dapat memilih bidang apa yang ingin Anda ketahui. Terimakasih telah berkunjung",
  closingEn: "Enjoy looking at my portfolio. You can choose the field that you want to see. Thanks for Visitting.",
};

export const dataProfSection = [
  {
    id: "psnull",
    nameEn: "You haven`t chosen a profession",
    nameId: "Anda belum memilih profesi",
  },
  {
    id: "pswt",
    nameEn: "Writer & Translation",
    nameId: "Kepenulisan & Penerjemahan",
    data: {
      skill: [
        {
          id: "skill-sw",
          skillName: "SEO Writer",
          imgUrl: "https://i.imgur.com/pRKb8tT.jpg",
        },
        {
          id: "skill-grammar",
          skillName: "Grammar",
          imgUrl: "https://i.imgur.com/t4B5ONl.jpg",
        },
        {
          id: "skill-editing",
          skillName: "Script Editing",
          imgUrl: "https://i.imgur.com/nOxlUhL.jpg",
        },
        {
          id: "skill-idea",
          skillName: "Idea Writing",
          imgUrl: "https://i.imgur.com/1jQaiQD.jpg",
        },
        {
          id: "skill-msword",
          skillName: "Ms. Word",
          imgUrl: "https://i.imgur.com/Ld3dl12.png",
        },
        {
          id: "skill-translate",
          skillName: "Translating",
          imgUrl: "https://i.imgur.com/46MySlC.jpg",
        },
      ],
      achievement: [
        {
          id: "ach-ssw",
          figcaptionID: "Penulisan Cerpen",
          figcaptionEN: "Short Story Writing",
          aNameEN: `Writing Seminar with the theme "How to Write Short Stories and Novels"`,
          aNameID: `Seminar Kepenulisan yang Bertemakan "Cara Menulis Cerpen dan Novel"`,
          institude: "Esamedia",
          imgUrl: "https://i.imgur.com/KbbgM5O.jpg",
          descId: "Ini adalah seminar yang pernah saya ikuti pada tahun 2021. Di dalamnya, saya mempelajari bagaimana cara mencari ide, mengembangkan premis, dan lain sebagainya.",
          descEn: "This is a seminar I attended in 2021. In it, I learned how to find ideas, develop a premise, and so on.",
        },
        {
          id: "ach-aw",
          figcaptionID: "Penulisan Akademik",
          figcaptionEN: "Academic Writing",
          aNameEN: `Academic Writing Workshop: Writing Articles for Beginners`,
          aNameID: `Workshop Penulisan Akademik : Menulis Artikel bagi Pemula`,
          institude: "UIN Aalauddin Makassar",
          imgUrl: "https://i.imgur.com/PNWBP9Q.png",
          descId: "Ini adalah seminar yang pernah saya ikuti pada tahun 2021. Di dalamnya, saya mempelajari bagaimana cara penulisan dalam dunia akdemik.",
          descEn: "This is a seminar I attended in 2021. I learned how to write in academic world.",
        },
        {
          id: "ach-pw",
          figcaptionID: "Penulisan Puisi",
          figcaptionEN: "Poetry Writing",
          aNameEN: `Best Work in the Sweet Theme Poetry Contest`,
          aNameID: `Karya Terbaik dalam Lomba Puisi Tema Manis`,
          institude: "SPWS Publisher",
          imgUrl: "https://i.imgur.com/MzO6UEl.png",
          descId: "Ini adalah lomba mengarang puisi yang diadakan oleh SPWS Publisher pada tahun 2022. Saya mendapat kategori Karya Terbaik dalam lomba puisi ini.",
          descEn: "This is a poetry writing competition held by SPWS Publisher in 2022. I got the Best Work category in this poetry competition",
        },
        {
          id: "ach-bw",
          figcaptionID: "Penulisan Blog",
          figcaptionEN: "Blog Writing",
          aNameEN: `Participant in the Online Blog Writing Competition with the Theme "Different Stay Together"`,
          aNameID: `Partisipan dalam Kompetisi Online Penulisan Blog dengan Tema "Berbeda Tetap Bersama"`,
          institude: "PPIM UIN Jakarta & Convey Indonesia",
          imgUrl: "https://i.imgur.com/ab9SSlE.png",
          descId: "Ini adalah lomba menulis blog yang dilaksanakan oleh PPIM UIN Jakarta dan Convey Indonesia pada tahun 2021",
          descEn: "This is a blog  writing competition held by PPIM UIN Jakarta and Convey Indonesia in 2022.",
        },
        {
          id: "ach-ssw2",
          figcaptionID: "Penulisan Cerpen",
          figcaptionEN: "Short Story Writing",
          aNameEN: `Participant in Short Story Writing Competition"`,
          aNameID: `Partisipan dalam Lomba Penulisan Cerpen`,
          institude: "Alinea Media Pustaka",
          imgUrl: "https://i.imgur.com/B5aj1Qi.png",
          descId: "Ini adalah lomba menulis cerpen yang diadakan oleh Alinea Media Pustaka pada tahun 2021",
          descEn: "This is a Short Story writing competition held by Alinea Media Pustaka in 2022.",
        },
      ],
      creativity: [
        {
          id: "cr-bw",
          figcaptionEN: "Book Writing",
          figcaptionID: "Penulisan Buku",
          pNameEN: "Book Writing",
          pNameID: "Penulisan Buku",
          date: "2021",
          imgUrl: "https://i.imgur.com/U9uKrSl.jpg",
          projectLink: "https://www.guepedia.com/book/20230",
          descId: "Ini adalah buku karya saya sendiri yang pertama. Buku ini membahas tentang bagaimana menjadi umat Islam kekinian dengan mengikuti zaman, namun tidak lupa dengan ajaran agama.            ",
          descEn: "This is my first own book. This book tells about how to be current muslim with following the era but no abandoning religion.",
        },
        {
          id: "cr-kw",
          figcaptionEN: "Kompasiana Writer",
          figcaptionID: "Penulis Kompasiana",
          pNameEN: "Writer in Kompasiana Media",
          pNameID: "Penulis di Media Kompasiana",
          date: "2023 - Now",
          imgUrl: "https://i.imgur.com/n2QQrvB.png",
          projectLink: "https://www.kompasiana.com/muhammadaqilmaulana3384",
          descId: "Saya menulis di media Kompasiana. Niche yang saya tampilkan beragam, namun lebih dominan ke masalah lifestyle.",
          descEn: "I`ve been writing in Kompasiana Media. The topic I write in and of kinds, but the majority is Lifestyle.",
        },
        {
          id: "cr-udw",
          figcaptionEN: "Urban Depok Writer",
          figcaptionID: "Penulis Urban Depok",
          pNameEN: "Writer in Urban Depok Media",
          pNameID: "Penulis di Media Urban Depok",
          date: "2023 - Now",
          imgUrl: "https://i.imgur.com/jQswAJg.png",
          projectLink: "https://depok.urbanjabar.com/author/24060/Muhamad-Aqil-Maulana",
          descId: "Saya menulis di media Urban Depok. Niche yang saya tampilkan beragam, namun lebih dominan ke masalah lifestyle.",
          descEn: "I`ve been writing in Urban Depok Media. The topic I write in and of kinds, but the majority is Lifestyle.",
        },
        {
          id: "cr-blw",
          figcaptionEN: "Blog Writer",
          figcaptionID: "Penulis Blog",
          pNameEN: "Writer in Blog",
          pNameID: "Penulis di Blog",
          date: "2023 - Now",
          imgUrl: "https://i.imgur.com/FRPOkb6.png",
          projectLink: "https://feros-blog.blogspot.com/",
          descId: "Saya menulis di blog pribadi. Niche yang saya tampilkan tentang peternakan, perikanan, dan juga pertanian.",
          descEn: "I`ve been writing in My personal blog. The topic I write in farming, fishing, and gardening.",
        },
        {
          id: "cr-blw2",
          figcaptionEN: "Blog Writer",
          figcaptionID: "Penulis Blog",
          pNameEN: "Writer in Blog",
          pNameID: "Penulis di Blog",
          date: "2023 - Now",
          imgUrl: "https://i.imgur.com/rddUI5y.png",
          projectLink: "https://gamelingo30.blogspot.com/",
          descId: "Saya menulis di blog pribadi. Sesuatu yang saya tulis adalah tentang penyajian data dan informasi dari suatu game. Nantinya, akan ada banyak game yang ditampilkan dalam situs tersebut.",
          descEn: "I write on a personal blog. Something I wrote was about presenting data and information from a game. In the future, there will be many games displayed on the site",
        },
      ],
    },
  },
  {
    id: "psfed",
    nameId: "Front End Developer",
    nameEn: "Front End Developer",
    data: {
      lang: [
        {
          id: "lang-html",
          langName: "HTML",
          imgUrl: "https://i.imgur.com/DDnamRu.png",
        },
        {
          id: "lang-css",
          langName: "CSS",
          imgUrl: "https://i.imgur.com/yYyJHzW.png",
        },
        {
          id: "lang-bootstrap",
          langName: "Bootstrap",
          imgUrl: "https://i.imgur.com/VedGM4l.png",
        },
        {
          id: "lang-sass",
          langName: "SASS",
          imgUrl: "https://i.imgur.com/dpqOxCg.png",
        },
        {
          id: "lang-js",
          langName: "Javascript",
          imgUrl: "https://i.imgur.com/xJvECB8.png",
        },
        {
          id: "lang-jQuery",
          langName: "jQuery",
          imgUrl: "https://i.imgur.com/78ivJxv.png",
        },
        {
          id: "lang-node",
          langName: "Node Js",
          imgUrl: "https://i.imgur.com/92dWMyV.png",
        },
        {
          id: "lang-express",
          langName: "Express Js",
          imgUrl: "https://i.imgur.com/23FTroI.png",
        },
        {
          id: "lang-react",
          langName: "React Js",
          imgUrl: "https://i.imgur.com/H4AfQst.png",
        },
      ],
      achievement: [
        {
          id: "ach-rwd",
          figcaption: "HTML CSS",
          achievementaName: "Responsive Web Design",
          institude: "Freecodecamp",
          link: "https://www.freecodecamp.org/certification/aqil2514/responsive-web-design",
          imgUrl: "https://i.imgur.com/arAWMFU.png",
          descId:
            "Ini adalah awal saya mempelajari berbagai macam mengenai HTML dan CSS. Dalam HTML, saya sudah menguasai beberapa hal yang diperlukan oleh kebutuhan sebagian besar industri. Dalam CSS, saya sudah menguasai sintaks dasar, selector css, box model, tipe teks dan tipografi, layouting dan positioning, background dan warna, media query, animation.",
          descEn:
            "This is my first learning about anything about HTML and CSS. In HTML, I`ve mastered few things that be needed by industries. In CSS, I`ve mastered about basic sytax, css selector, box model, text type and typhography, layouting and positioning, background and color, media query, and animation.",
        },
        {
          id: "ach-jaads",
          figcaption: "JavaScript",
          achievementaName: "JavaScript Algorithms and Data Structures",
          institude: "Freecodecamp",
          link: "https://www.freecodecamp.org/certification/aqil2514/javascript-algorithms-and-data-structures",
          imgUrl: "https://i.imgur.com/a1ewjvY.png",
          descId: "Ini adalah langkah selanjutnya saya setelah mempelajari HTML dan CSS. Di sesi ini, saya mempelajari dasar-dasar dari Javascript.",
          descEn: "This is my next step in learning HTML and CSS. In this session, I learned basics of Javascript.",
        },
        {
          id: "ach-fcse",
          figcaption: "Fundamental",
          achievementaName: "Fundamental Course of Software Engineering",
          institude: "RevoU",
          link: "https://aqil2514.github.io/KalTik/",
          imgUrl: "https://i.imgur.com/ZQLgY96.png",
          descId: "Ini adalah kursus gratis pertama saya dalam bidang Software Engineering. Output dari kursus ini adalah diharuskannya membuat sebuah kalkulator yang menghitung luas dan keliling persegi.",
          descEn: "This is my first free course in Software Engineering. The output of this course is making a calculator which calculating the area and perimeter of a rectangle ",
        },
      ],
      creativity: [
        {
          id: "cr-sf",
          projectName: "Survey Form",
          languages: "HTML, CSS",
          date: "23/3/2023",
          imgUrl: "https://i.imgur.com/TPztbl6.png",
          projectLink: "https://aqil2514.github.io/survey-form/",
          sourceLink: "https://github.com/aqil2514/survey-form",
          descId:
            "Ini adalah project pertama saya dengan menggunakan HTML dan CSS saja. Ini juga merupakan project dari persyaratan sertifikat FreeCodeCamp pada materi Responsive Web Design. Di dalamnya, tersedia element table dengan beberapa input berbagai type.",
          descEn: "This my first project in HTML and CSS. This also the requirements to get FreeCodeCamp's certificate on Responsive web Design. Inside, there are input elements with kinds of type.",
        },
        {
          id: "cr-tp",
          projectName: "Tribute Page",
          languages: "HTML, CSS",
          date: "26/3/2023",
          imgUrl: "https://i.imgur.com/XdFFM2P.png",
          projectLink: "https://aqil2514.github.io/tribute-page/",
          sourceLink: "https://github.com/aqil2514/tribute-page",
          descId:
            "Ini adalah project kedua saya dengan menggunakan HTML dan CSS saja. Ini juga merupakan project dari persyaratan sertifikat FreeCodeCamp pada materi Responsive Web Design. Di dalamnya, tersedia beberapa hal yang menjelaskan tentang riwayat pendidikan saya.",
          descEn: "This my second project in HTML and CSS. This also the requirements to get FreeCodeCamp's certificate on Responsive web Design. Inside, there are few about my educations.",
        },
        {
          id: "cr-sj",
          projectName: " Suwit Jawa",
          languages: "HTML, CSS, JavaScript",
          date: "26/3/2023",
          imgUrl: "https://i.imgur.com/Ky3848Y.png",
          projectLink: "https://aqil2514.github.io/suit-jawa/",
          sourceLink: "https://github.com/aqil2514/suit-jawa",
          descId:
            "Ini adalah project pertama saya dengan menggunakan HTML, CSS, dan Javascript. Ini adalah sebuah game sederhana tentang suit jawa. Di dalamnya, sudah ditambahkan AI computer, sistem score, menang kalah, dan beberapa komponen lain.",
          descEn: "This is my first project with Javascript. This is a simple game about Suit Jawa. Inside, there is simple AI, sccore system, win and lose.",
        },
        {
          id: "cr-gg",
          projectName: "Genshin Gallery",
          languages: "HTML, CSS, jQuery, Bootstrap",
          date: "30/5/2023",
          imgUrl: "https://i.imgur.com/3hT8e3M.jpg",
          projectLink: "https://aqil2514.github.io/Gallery-Genshin-Impact",
          sourceLink: "https://github.com/aqil2514/Gallery-Genshin-Impact",
          descId:
            "Ini adalah project pertama saya dengan menggabungkan framework, library, dan pre-proccesor menjadi satu. Saya membuat sebuah situs sederhana dengan Slide Image yang dibuat menggunakan jQuery. Tidak hanya itu, saya juga mengatur apabila gambarnya berganti, makan background imagenya juga berganti.",
          descEn: "This is my first project with combinating framework, library, and css pre-processor. I made a very simple site with Image Slider made by jQuery. The background also change if the image change.",
        },
        {
          id: "cr-tf",
          projectName: "Team Flow",
          languages: "HTML, SASS, jQuery",
          date: "10/9/2023",
          imgUrl: "https://i.imgur.com/bWzjdRf.png",
          projectLink: "https://aqil2514.github.io/team-flow/",
          sourceLink: "https://github.com/aqil2514/team-flow",
          descId: "Ini adalah challenge dari situs codedesign.dev. Project ini tidak didesain Mobile Friendly",
          descEn: "This a challenge from codedesign.dev. This project is not Mobile Friendly",
        },
        {
          id: "cr-grq",
          projectName: "Genshin Random Quote",
          languages: "HTML, React JS, SASS",
          date: "13/9/2023",
          imgUrl: "https://i.imgur.com/hy5Xe3i.jpg",
          projectLink: "https://aqil2514.github.io/Genshin-Random-Quote/",
          sourceLink: "https://github.com/aqil2514/Genshin-Random-Quote",
          descId: "Project pribadi saya dalam menuntaskan sertifikat Front End Development Library di FreeCodeCamp. Masih ada bug.",
          descEn: "My private project in Front End Development Library in FreeCodeCamp. Still there`s a bug.",
        },
      ],
    },
  },
  {
    id: "psve",
    nameEn: "Video Editing",
    nameId: "Video Editing",
    data: {
      skill: [
        {
          id: "skill-km",
          skillName: "Kine Master",
          imgUrl: "https://i.imgur.com/5dWxCXT.png",
        },
        {
          id: "skill-capcut",
          skillName: "Capcut",
          imgUrl: "https://i.imgur.com/DBEhSNC.png",
        },
      ],
      achievement: [],
      creativity: [
        {
          id: "cr-gv",
          figcaptionEN: "Game Video",
          figcaptionID: "Video Game",
          pNameEN: "Game Video",
          pNameID: "Video Game",
          date: "2022",
          imgUrl: "https://i.imgur.com/sj83wz8.png",
          projectLink: "https://www.tiktok.com/@clevergaming293",
          descId: "Ini adalah video yang saya edit menggunakan Kinemaster dan Capcut di bidang video game",
          descEn: "This video is editted by using Kinemaster and Capcut.",
        },
        {
          id: "cr-tv",
          figcaptionEN: "Subtitle Video",
          figcaptionID: "Video Subtitle",
          pNameEN: "Subtitle Video",
          pNameID: "Video Subtitle",
          date: "2022 - 2023",
          imgUrl: "https://i.imgur.com/pIEX8qZ.png",
          projectLink: "https://www.youtube.com/playlist?list=PLlgbBAiExG5l22QseRAPc1b0I0mw24TVo",
          descId: "Ini adalah video yang saya terjemahkan dari bahasa Arab ke dalam bahasa Indonesia. Video ini berasal dari situs Kids Islamweb.",
          descEn: "This video is translated by me from Arabic to Indonesia. The source is from Kids IslamWeb",
        },
        {
          id: "cr-pv",
          figcaptionEN: "Promotion Video",
          figcaptionID: "Video Promosi",
          pNameEN: "Promotion Video",
          pNameID: "Video Promosi",
          date: "2022",
          imgUrl: "https://i.imgur.com/58Gix4h.png",
          projectLink: "https://www.youtube.com/watch?v=iM7ZycUXfiY",
          descId: "Ini adalah video yang saya buat untuk memenuhi tugas perkuliahan. Video ini menceritakan bahwa saya menjadi seseorang yang mempromosikan tempat wisata yang ada di Depok menggunakan bahasa Arab.",
          descEn: "This is a video I made to fulfill a lecture assignment. This video tells the story of me being someone who promotes tourist attractions in Depok using Arabic.",
        },
      ],
    },
  },
];
